# api-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
      version: v1
  template:
    metadata:
      labels:
        app: api
        version: v1
    spec:
        serviceAccount: api
        serviceAccountName: api
        containers:
          - name: api
            image: qjoly/kubernetes-coffee-image:api
            imagePullPolicy: Always
            ports:
              - containerPort: 80
                name: http
            resources:
              limits:
                cpu: "0.5"
                memory: "512Mi"
              requests:
                cpu: "0.1"
                memory: "256Mi"
            livenessProbe:
              httpGet:
                path: /
                port: http
              initialDelaySeconds: 3
              periodSeconds: 3
              timeoutSeconds: 1
              successThreshold: 1
              failureThreshold: 3
            readinessProbe:
              httpGet:
                path: /
                port: http
              initialDelaySeconds: 3
              periodSeconds: 3
              timeoutSeconds: 1
              successThreshold: 1
              failureThreshold: 3
---

# api-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
    version: v1
spec:
  selector:
    app: api
    version: v1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
--- 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  labels:
    account: api
