# frontend-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      version: v1
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
        serviceAccount: frontend
        serviceAccountName: frontend
        containers:
          - name: frontend
            image: qjoly/kubernetes-coffee-image:frontend
            ports:
              - name: http
                containerPort: 80
            imagePullPolicy: Always
            env:
              - name: COFFEE_SERVER_API
                value: "http://api:80"
              - name: POD_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
            resources:
              limits:
                cpu: "1"
                memory: "512Mi"
              requests:
                cpu: "0.1"
                memory: "256Mi"
            livenessProbe:
              httpGet:
                path: /
                port: http
              initialDelaySeconds: 5
              periodSeconds: 5
              timeoutSeconds: 2
              successThreshold: 1
              failureThreshold: 3
            readinessProbe:
              httpGet:
                path: /
                port: http
              initialDelaySeconds: 3
              periodSeconds: 3
              timeoutSeconds: 1
              successThreshold: 1
              failureThreshold: 3
---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    version: v1
spec:
  selector:
    app: frontend
    version: v1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  labels:
    account: frontend